WIP: Adding auto creation of manila share
stackhpc/azimuth pull request #148
Opened 2024-01-18 11:27 UTC by JohnGarbutt

2024-01-24 09:07 UTC, sjpb commented on api/azimuth/provider/openstack/provider.py
> +            default_share_type = None
Note Arcus's rcp-cloud-portal-demo doesn't have a default share type defined, hence https://github.com/stackhpc/ansible-slurm-appliance/pull/344 defines `cluster_home_manila_share_type`.

2024-01-24 09:07 UTC, sjpb commented on api/azimuth/provider/openstack/provider.py
> +        self._project_share_name = "azimuth-project-share"
Yep matches default in https://github.com/stackhpc/ansible-slurm-appliance/pull/344

2024-01-24 10:59 UTC, mkjpryor requested changes
I'm still also unconvinced about gating this on the `create_manila_project_share` boolean.

Don't we want it to be done whenever Manila with the Ceph driver is available?

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/api/shares.py
I think for consistency with the rest of the code, this module should be called `share`? Everything else is singular, as is the name of the service in the catalog.

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/api/core.py
> +                request.headers["X-OpenStack-Manila-API-Version"] = f"{self.microversion}"
This is service-specific, so should be in the specific service (i.e. remove from here).

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/api/shares.py
> +    access = RootResource(ShareAccess)
Override `prepare_request` here and add the Manila-specific microversion header.

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise Exception("Share has a problem with its access rules!")
Raise the relevant exceptions from here: https://github.com/stackhpc/azimuth/blob/master/api/azimuth/provider/errors.py

These are converted nicely into API errors with nice messages, rather than generic 500 errors.

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise Exception("can't find the expected access rule!")
Also here

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise Exception("Unable to find valid share type!")
And here

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +        self._project_share_name = "johng-dev"
This needs un-johng-ing right?

2024-01-24 10:59 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                time.sleep(0.1)
Does this not have an error case where the share does not become available within the allotted time?

2024-01-24 11:54 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +        self._project_share_name = "johng-dev"
oops, I left that in!

2024-01-24 11:55 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +            default_share_type = None
yeah, if there is only one share type, I just use that instead. We could configure it.

2024-01-24 11:57 UTC, JohnGarbutt commented
> Don't we want it to be done whenever Manila with the Ceph driver is available?

No, because of the networking requirements. It only works when it works.

Thinking about that... I probably need to simply not create a share in the case where we can't find a valid share type, as that is the way a project being setup for manila can be checked on Arcus, and its a good solution I think.

2024-01-24 11:59 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +                time.sleep(0.1)
It does, but that currently falls through to the next call which will fail and raise an exception.

Its lazy though... I should raise an exception when you get an error status back.

2024-01-24 12:01 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/api/core.py
> +                request.headers["X-OpenStack-Manila-API-Version"] = f"{self.microversion}"
I agree, although can you tell me how please?
I don't really understand how to do that with your lib.

2024-01-24 12:01 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/api/shares.py
ah, yes, sure.

2024-01-24 12:02 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/api/shares.py
> +    access = RootResource(ShareAccess)
ah.. OK.

2024-01-24 12:05 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/api/core.py
> +                request.headers["X-OpenStack-Manila-API-Version"] = f"{self.microversion}"
ah, I see.

2024-01-24 12:13 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +            default_share_type = None
I am making it fail silently if I can't find any storage types, as on arcus it means they project isn't setup for Manila with the correct networking, etc.

2024-01-29 13:52 UTC, mkjpryor requested changes

2024-01-29 13:52 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise errors.Error("Share is not available!")
I think this should also be `ImproperlyConfiguredError`, as in the tenancy is not properly configured to support this feature.

2024-01-29 13:52 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise errors.Error("Share has a problem with its access rules!")
And this

2024-01-29 14:19 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +                raise errors.Error("Share is not available!")
I think this is a server error, so internal error seems good, but OK.

2024-01-30 11:36 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise errors.Error("Share has a problem with its access rules!")
It can be fixed by making changes in OpenStack though right? So it isn't really a server error in the usual sense.

2024-01-30 11:38 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +                raise errors.Error("Share has a problem with its access rules!")
It also reports as a 500 in the API, which is correct as you say.

2024-01-30 11:43 UTC, mkjpryor requested changes

2024-01-30 11:43 UTC, mkjpryor commented on api/azimuth/provider/openstack/api/share.py
> +        request.headers["X-OpenStack-Manila-API-Version"] = "2.51"
Not really sure how this has worked (have you tested it since this change?), since it should need to return the request rather than `None`. This code path is not used in the CI test suite which explains why it passed CI.

Anyway - this should call the method on the superclass to make sure the request is prepared correctly:

```python
def prepare_request(self, request):
    request.headers["X-OpenStack-Manila-API-Version"] = "2.51"
    return super().prepare_request(request)
```

2024-01-30 13:32 UTC, JohnGarbutt commented
Needs a quick final test.

2024-01-30 13:33 UTC, mkjpryor approved these changes
LGTM

2024-01-30 17:39 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +                size=10,
So we need to make this configurable... its probably not a bad value that we can use instead of true/false.

2024-01-31 10:52 UTC, merged