Record username and user_id for caas clusters
stackhpc/azimuth pull request #152
Opened 2024-01-24 09:42 UTC by JohnGarbutt

2024-01-24 11:53 UTC, JohnGarbutt commented
Note, you can try these on my dev setup here:
http://portal.apps.128-232-226-118.sslip.io/

2024-01-25 09:35 UTC, JohnGarbutt commented on api/azimuth/cluster_api/dto.py
> +    is_mine: bool
I am not sure I like its, maybe created_by_current_user is better?

2024-01-25 15:31 UTC, mkjpryor requested changes
Just a few unused variables and propagation thereof to remove.

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +    def _from_api_cluster(self, cluster, sizes, user_id):
`user_id` is passed in but not used

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +            return tuple(self._from_api_cluster(c, sizes, user_id) for c in clusters)
Passing of `user_id` is not required (see above)

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        return self._from_api_cluster(cluster, sizes, user_id)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        return self._from_api_cluster(cluster, sizes, user_id)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        return self._from_api_cluster(cluster, sizes, user_id)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        return self._from_api_cluster(cluster, sizes, user_id)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +def get_cluster_dto(raw_cluster, user_id, status_if_ready: dto.ClusterStatus = None):
`user_id` is passed but not used

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +def get_clusters(client, ctx: dto.Context) -> t.Iterable[dto.Cluster]:
`ctx` is passed but not required

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +        cluster = get_cluster_dto(raw_cluster, ctx.user_id)
Passing of user ID is not required

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +    return get_cluster_dto(cluster, ctx.user_id)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +    return get_cluster_dto(raw_cluster,  ctx.user_id, status_if_ready=dto.ClusterStatus.DELETING)
Same

2024-01-25 15:31 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +    return get_cluster_dto(raw_cluster,  ctx.user_id, status_if_ready=dto.ClusterStatus.CONFIGURING)
Same

2024-01-29 12:47 UTC, JohnGarbutt commented on api/azimuth/cluster_api/base.py
> +    def _from_api_cluster(self, cluster, sizes, user_id):
oops, yes 😵‍💫

2024-01-30 11:47 UTC, mkjpryor requested changes

2024-01-30 11:47 UTC, mkjpryor commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +                    <td>{cluster.created_by_username ? cluster.created_by_username : '-'}</td>
`cluster.created_by_username || '-'` is sufficient here and avoids repetition. Similarly elsewhere.

2024-01-30 11:47 UTC, mkjpryor commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +                    <td>{cluster.created_by_username ? cluster.created_by_username : '-'}</td>
Also, do we want `-` and not `unknown` or similar?

2024-01-30 11:47 UTC, mkjpryor commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +                Created by {cluster.created_by_username ? cluster.created_by_username : '-'}
Personally, I prefer "Created X mins ago by <user>". Do you have a strong preference for this format?

2024-01-30 13:36 UTC, JohnGarbutt commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +                Created by {cluster.created_by_username ? cluster.created_by_username : '-'}
it looked odd, not sure by the two lines either.

2024-01-30 13:40 UTC, JohnGarbutt commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +                    <td>{cluster.created_by_username ? cluster.created_by_username : '-'}</td>
done.

2024-01-30 13:40 UTC, mkjpryor approved these changes
LGTM

2024-01-30 13:41 UTC, JohnGarbutt commented
Needs final tests.

2024-01-30 16:03 UTC, JohnGarbutt commented
I have manually retested this, ant its looking as expected

2024-01-30 16:04 UTC, merged