WIP: Allow filtering application catalog based on OpenStack tenancy
stackhpc/azimuth pull request #174
Opened 2024-02-15 15:44 UTC by sd109

2024-02-15 21:43 UTC, mkjpryor requested changes
This is looking pretty good I think. Just a handful of minor things.

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        templates = list(filter(lambda t: allowed_by_acls(t, tenancy), templates))
Use a list comprehension here - they are more readable

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +            raise errors.InvalidOperationError(f"Cannot fetch cluster template {id} - template blocked by tenancy ACLs")
Security best practice is to return not found when a resource is denied by access control, to avoid leaking information about valid resources.

In practice, that means raising `ObjectNotFound` here I think.

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +        templates = list(filter(lambda t: allowed_by_acls(t, tenancy), templates))
List comprehension

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +            raise errors.InvalidOperationError(f"Cannot fetch app template {id} - template blocked by tenancy ACLs")
Not found

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +        raise errors.InvalidOperationError(f"Cannot update cluster {name} - cluster type blocked by ACLs in tenancy {ctx.tenancy.id}")
Not found

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/utils.py
Rename to `acl.py`?

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/utils.py
> +    elif ACL_ALLOW_IDS_KEY in annotation_keys:
`elif` is the wrong logic here. We want to try each test in turn until we hit a match. 

With the current logic, a tenancy that matches the deny regex would be granted access if the deny list annotation exists but does not contain its id.

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/utils.py
> +        denied_tenancies = annotations[ACL_DENY_IDS_KEY]
Don’t we need to split this on `,`? Or are we happy relying on ids never having commas in? Probably true, but splitting feels more correct.

2024-02-15 21:43 UTC, mkjpryor commented on api/azimuth/utils.py
> +    return True
This should be false if either allow annotation is present, true if not. This is because if an allow annotation is present, the intention is to deny access to things that don’t match.

2024-02-15 21:43 UTC, mkjpryor commented on ui/src/components/pages/tenancy/platforms/clusters/card.js
> +    logo: azimuthLogo,
Not convinced by the Azimuth logo here. I think we should use something more generic. Maybe a sad face or a ban icon, in grey.

2024-02-15 21:43 UTC, mkjpryor commented on ui/src/components/pages/tenancy/platforms/kubernetes/card.js
> +                            <h5 className="text-center">WARNING: Kubernetes functionality is no longer available in this tenancy.</h5>
Use an `Error` here, as discussed on Slack

2024-02-16 16:33 UTC, sd109 commented on api/azimuth/cluster_api/base.py
> +            raise errors.InvalidOperationError(f"Cannot fetch cluster template {id} - template blocked by tenancy ACLs")
That's sensible, fixed.

2024-02-16 17:25 UTC, mkjpryor requested changes

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +        is_allowed = tenancy.id in allowed_tenancies
This should return immediately if the tenancy is in the list, with the value `True`. If the tenant is not in the list, it should fall through to the other contraints.

The list takes precedence over any regexes so we only need to consider the other constraints if the tenancy is not in this list. This is so we can fulfil the case where you use a broad regex to deny, but want to allow one or two tenants.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +        return re.match(pattern, tenancy.name) is None
This should return immediately if the tenancy matches the regex, with the value `False`. If the tenant does not match the regex, it should fall through to the other constraints.

The current logic would mean `True` (i.e. allow) is returned immediately if the deny regex exists but the tenancy does not match, without checking any other constraints (e.g. if we should default to deny).

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +        is_allowed = re.match(pattern, tenancy.name) is not None
This should return immediately if the tenancy matches the regex, with the value `True`. If the tenant does not match the regex, it should fall through to the default.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +    is_allowed = not (
You don't need to track this value through the computation, as each annotation is considered independently, essentially. It is the order that we check them that gives the precedence.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +        return True
This is redundant, since it falls out of all the other logic. I'm happy to keep it if you think it is clearer.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +    annotation_keys = annotations.keys()
This is not necessary, because `key in annotations` works.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +    return is_allowed
This can just be

```python
return (
    ACL_ALLOW_IDS_KEY not in annotations and
    ACL_ALLOW_PATTERN_KEY not in annotations
)
```

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/test_acls.py
If we are going to test, let's test more cases. E.g.:

* `deny-list` and `deny-regex` are both present
* Tenancy is not in the list but matches the regex
* Should return `False` (i.e. deny) - note that this would return `True` with the current code

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/acls/__init__.py
Import the `allowed_by_acls` function in here.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +from ..acls.acls import allowed_by_acls
If we import `allowed_by_acls` in `__init__.py` for the `acls` module, we can get rid of the horrible `acls.acls` here.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +from ....acls.acls import allowed_by_acls
Same here

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +            raise errors.ObjectNotFoundError(f"Cannot find cluster template {id} in tenancy.")
I think the `in tenancy` is not necessary here, and in fact implies that it might be valid in another tenancy.

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_api/base.py
> +            raise errors.ObjectNotFoundError(f"Cannot find app template {id} in tenancy {tenancy.id}")
Same here

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +        raise errors.ObjectNotFoundError(f"Cannot find cluster type {cluster_type_name} in tenancy {tenancy.id}")
Remove `in tenancy`

2024-02-16 17:25 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +        raise errors.ObjectNotFoundError(f"Cannot update cluster {name} - cluster type not found in tenancy {ctx.tenancy.id}")
Remove `in tenancy ...`

2024-02-16 17:31 UTC, mkjpryor commented on api/azimuth/acls/acls.py
> +    annotation_keys = annotations.keys()
Also, if the goal of the previous line is for `annotations` to always be a dict, it should be this:

```python
annotations = raw.get("metadata", {}).get("annotations", {})
```

2024-02-19 10:39 UTC, sd109 commented on api/azimuth/acls/acls.py
> +        return True
True, but let's keep it for clarity

2024-02-29 14:49 UTC, mkjpryor approved these changes
LGTM

2024-02-29 14:49 UTC, merged