add storage network to cluster params
stackhpc/azimuth pull request #236
Opened 2024-05-28 11:32 UTC by scrungus

adds a network tagged 'portal-storage-direct' to cluster params

2024-05-28 12:04 UTC, JohnGarbutt requested changes
I think this looks good, thank you.

Although please get the test passing before we merge. It looks like something is out of quota.

... but lets make that tag simpler for now.

2024-05-28 12:04 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +        tagged_network = self._tagged_network("storage-direct")
Sorry, I am changing my mind here, but I think we want to call this just "storage" similar to "external" and "internal" tags we used above.

2024-05-28 12:06 UTC, JohnGarbutt requested changes

2024-05-28 12:06 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +            params['cluster_storage_network'] = storage_network.name
I think this should probably come from config, but lets hard code this, for now:

`params['cluster_storage_network_vnic_type'] = "direct"`

2024-05-28 12:15 UTC, scrungus commented on api/azimuth/provider/openstack/provider.py
> +            params['cluster_storage_network'] = storage_network.name
alternatively, If we want to follow the same pattern as the `vnic_type` for the primary network, we could do: 

```
binding {
    vnic_type = "{{ cluster_storage_vnic_type | default('direct') }}"
  }
 ```
 
 in the terraform resources? seeing as we don't pass in `cluster_vnic_type` from azimuth.

2024-05-28 12:24 UTC, JohnGarbutt commented on api/azimuth/provider/openstack/provider.py
> +            params['cluster_storage_network'] = storage_network.name
So in this case, I think we want to keep "normal" as the default, but Azimuth is say thing it is the vnic_port direct, because the tag is "storage-direct" and not "storage".

2024-05-30 15:34 UTC, mkjpryor approved these changes
LGTM

2024-05-31 09:46 UTC, JohnGarbutt approved these changes
Cool, this looks good now, thank you.

2024-05-31 11:08 UTC, merged