Add new caas driver for CRD
stackhpc/azimuth pull request #31
Opened 2023-01-24 14:55 UTC by JohnGarbutt

2023-03-30 18:09 UTC, JohnGarbutt commented on chart/templates/api/settings.yaml
> +      CAAS_CRD:
@mkjpryor I think its going to be quicker if you make this change in the helm, I am a bit lost with all of the configuration options in there. We should talk about options to simplify the templates in here.

2023-03-30 18:11 UTC, JohnGarbutt commented on api/azimuth/settings.py
> +            return Engine(driver, instance.APPS)
this is clearly horrendous, I just make it win if AWX is also enabled.

2023-04-12 09:35 UTC, mkjpryor requested changes

2023-04-12 09:35 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +                return cluster
This is going to become more and more inefficient the more clusters there are, similar to the existing AWX implementation (but probably not as bad).

Please can we use the name as the ID to avoid this, rather than fighting against the Kubernetes semantics?

2023-04-12 09:35 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +                            # NOTE(johngarbutt): skip project_id so cli works
You can remove this comment - `project_id` being required in the appcred is a gophercloud quirk that is required for CAPI.

2023-04-12 09:35 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/awx/driver.py
> +        cloud_session
Add the type here

2023-04-12 09:35 UTC, mkjpryor commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +    # TODO(johngarbutt): is this racing the operator?
It can be, especially if the operator is down for some reason, which is why the code that interacts with the Azimuth CAPI operator CRDs includes some code to spot if the operator hasn't yet acted on the resource. There isn't a lot else we can do about it unfortunately.

2023-04-12 09:35 UTC, mkjpryor commented on api/azimuth/settings.py
> +            return Engine(driver, instance.APPS)
Yeah - this clearly needs some work

2023-04-12 09:46 UTC, JohnGarbutt commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +    return f"caas-{safe_project_id}"
Well zero chance of two versions of the operators, but yes.  I need a hand with your magic configuration stuff, I couldn't get my head around how it worked.

2023-04-12 09:52 UTC, JohnGarbutt commented on api/azimuth/cluster_engine/drivers/crd/driver.py
> +                return cluster
OK, so what are the properties of the id, and why do we have one in addition to the name? I am confused if they are both the same?

I don't disagree that its a horrible hack, although at least its only a per namespace iteration, so I wasn't so bothered by it.

2023-06-01 16:43 UTC, JohnGarbutt commented on api/azimuth/cluster_engine/drivers/awx/driver.py
> +        cloud_session
what is the type, I wasn't sure?

2023-06-29 08:31 UTC, mkjpryor commented
Closed in favour of #54

2023-06-29 08:31 UTC, closed without merging