Remove admin role from application credential
stackhpc/azimuth pull request #65
Opened 2023-09-15 14:06 UTC by bbezak

2023-09-15 14:22 UTC, JohnGarbutt approved these changes
Nice, great job.

2023-09-15 14:37 UTC, mkjpryor requested changes
Nice work. Just a minor thing, in case we want to use the roles for something else in future.

2023-09-15 14:37 UTC, mkjpryor commented on api/azimuth/provider/openstack/api/core.py
> +        self.roles = [{'name': role['name']} for role in roles_data]
Personally, I would prefer that this stores the actual thing returned by the token endpoint, i.e. just:

```python
self.roles = json["token"].get("roles", [])
```

That way, we have all the role information if we want it for something else in the future.

2023-09-15 14:37 UTC, mkjpryor commented on api/azimuth/provider/openstack/provider.py
> +            roles=roles_without_admin,
And this does the conversion into the specific `{"name": "<rolename>"}` syntax required by this API call, e.g.:

```python
app_cred_roles = [
    {"name": role["name"]}
    for role in self._connection.roles
    if role["name"] != "admin"
]
```

2023-09-18 13:06 UTC, bbezak commented on api/azimuth/provider/openstack/api/core.py
> +        self.roles = [{'name': role['name']} for role in roles_data]
done

2023-09-18 13:06 UTC, bbezak commented on api/azimuth/provider/openstack/provider.py
> +            roles=roles_without_admin,
done

2023-09-19 09:35 UTC, mkjpryor approved these changes
LGTM

2023-09-19 09:35 UTC, merged